development:
  adapter: postgresql
  database: schwank_development
  encoding: utf-8
  username: postgres
  password:
  pool: 5
  timeout: 5000
  host: localhost
test:
  adapter: postgresql
  database: schwank_test
  encoding: utf-8
  username: postgres
  password:
  pool: 5
  timeout: 5000
  host: localhost
